### ISSUE TITLE
categorias en paginas de HOMBRES

### ISSUE THREAD

**Issue by anilentp** [lpagency/placare#43]
en las paginas de hombres y sus paginas de categorías, estos filtros no deben aparecer:   
Tipo de Taco       
Altura Taco       
Altura Plataforma
![screenshot-placare sites ondev today-2018 05 07-11-47-53](https://user-images.githubusercontent.com/17776341/39708370-5aaf2336-51ed-11e8-9f69-045b109f4599.png)

**Comment by k1ltr0** [comment]
resuelto con #41

**Comment by anilentp** [comment]
Los filtros que no iban, eran los 3 que estaban en el cuadro rojo (tipo de taco, altura de taco, altura de plataforma) las tallas debe estar para poder filtrar
