### ISSUE TITLE
iphones filtros no se ven completos

### ISSUE THREAD

**Issue by anilentp** [lpagency/placare#45]
iphone 4, 5, 6/7/8, 6/7/8plus  filtros no se ven completos, no baja 
![screenshot-placare sites ondev today-2018 05 07-11-58-46](https://user-images.githubusercontent.com/17776341/39709916-99d672b8-51f1-11e8-86d4-ad8a076e8466.png)

**Comment by k1ltr0** [comment]
solved with #41
